# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180513_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='Questionnaire',
            new_name='questionnaire',
        ),
    ]
