# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20180513_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='slug',
            new_name='userId',
        ),
    ]
