# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180513_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('userId', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_query', models.IntegerField(choices=[(1, b'Good'), (2, b'Regular'), (3, b'Bad')], default=None)),
                ('fastfood_query', models.IntegerField(choices=[(1, b'Good'), (2, b'Regular'), (3, b'Bad')], default=None)),
            ],
        ),
    ]
