# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fastfood_query',
            field=models.IntegerField(choices=[(1, b'Good'), (2, b'Regular'), (3, b'Bad'), (4, b'')], default=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='service_query',
            field=models.IntegerField(choices=[(1, b'Good'), (2, b'Regular'), (3, b'Bad'), (4, b'')], default=4),
        ),
        migrations.AlterField(
            model_name='response',
            name='fastfood_query',
            field=models.IntegerField(choices=[(1, b'Good'), (2, b'Regular'), (3, b'Bad'), (4, b'')], default=None),
        ),
        migrations.AlterField(
            model_name='response',
            name='service_query',
            field=models.IntegerField(choices=[(1, b'Good'), (2, b'Regular'), (3, b'Bad'), (4, b'')], default=None),
        ),
    ]
