# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20180513_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionnaire_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='userId',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
