# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20180513_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='userId',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
