# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20180513_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='userId',
            new_name='user',
        ),
    ]
