# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20180513_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fastfood_query',
            field=models.IntegerField(choices=[(1, b'Good'), (2, b'Regular'), (3, b'Bad'), (4, b'')], default=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='service_query',
            field=models.IntegerField(choices=[(1, b'Good'), (2, b'Regular'), (3, b'Bad'), (4, b'')], default=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
